Added markup for the html
Nasirkhan294/project-review-assignment pull request #1
Opened 2023-03-27 14:51 UTC by Nasirkhan294

Added html file
Added css file and Readme file

2023-03-27 15:03 UTC, AdnanOlarmmi requested changes
Hi @Nasirkhan294 😊,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Invalid Code Review Request 🆘💀
You have submitted a project, that doesn't have any review at all. You should review the pull request, the same version by which code reviewer review yours then submit the review for an external and professional review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2023-03-28 07:40 UTC, Nasirkhan294 reviewed
Hi @Nasirkhan294,

Hello! Thank you for sharing your code with me. I have reviewed it and here are my comments:

2023-03-28 07:40 UTC, Nasirkhan294 commented on index.html
> +    - The freeCodeCamp Team
It's good to see your code and you've done a great job. However, after completing your work consider deleting your comments because It makes your code messy and it's not a good practice as well.

2023-03-28 07:40 UTC, Nasirkhan294 commented on index.html
> +      </section>
In Text_section3, there is a code block without an opening tag. Please make sure to include opening and closing tags for the code block.

2023-03-28 08:17 UTC, OyePriscilla requested changes
Hi @Nasirkhan294 👍 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Good use of summary template ✔️ 
Good use of inline comments ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

**- [optional] I observed that your comments are the same all through, I will advise that you add one or more different issue(s). 👍** 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 08:17 UTC, OyePriscilla commented on index.html
> +      </section>
- [ ] Kindy, state the reason(s) for the suggested changes in a friendly manner, it may be obvious to you and not so for others. 👍

2023-03-28 08:17 UTC, OyePriscilla commented on index.html
> +      </nav>
- [ ] Kindy, state the reason(s) for the suggested changes in a polite manner, it may be obvious to you and not so for others. 👍

2023-03-28 09:19 UTC, Nasirkhan294 reviewed
Hi @Nasirkhan294,

Fantastic progress, you're so close! Let's keep up the momentum and tackle those remaining changes together. I have full confidence that we can get them done and achieve our goals.

![giphy](https://user-images.githubusercontent.com/71121832/228188818-8956b4a8-3dbd-4859-af6a-62f0fbd22aaf.gif)

## Highlights:

- [ ] No linter errors
- [ ] Good use of GitHub flow

2023-03-28 09:19 UTC, Nasirkhan294 commented on index.html
> +      </nav>
- [ ] Great job on adding a navigation bar to your technical documentation! However, the items in the navigation bar are currently empty and don't tell the user what each section is about. To improve, try adding descriptive text to each navigation item to guide users to the right section. This will make it easier for them to find what they're looking for and understand the content of your documentation.

2023-03-28 09:19 UTC, Nasirkhan294 commented on index.html
> +      </code>
- [ ] In Text_section3, the code block is missing an opening tag. It's essential to include both opening and closing tags for the code block to work properly. Don't worry, it's an easy fix! Just add the opening tag before the code block and the closing tag after it. This will ensure that the code runs smoothly.

2023-03-28 09:24 UTC, Strangeal approved these changes
Hi @Nasirkhan294, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Alt Text](https://media.giphy.com/media/JoSiL3L4ON8DlyVxv0/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 09:39 UTC, merged